/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.10 and Signal Processing Toolbox 8.6.
 * Generated on: 03-Aug-2021 12:16:38
 */

/*
 * Discrete-Time IIR Filter (real)
 * -------------------------------
 * Filter Structure    : Direct-Form II, Second-Order Sections
 * Number of Sections  : 2
 * Stable              : Yes
 * Linear Phase        : No
 */

/* General type conversion for MATLAB generated C-code  */
#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * C:\Program Files\MATLAB\R2021a\extern\include\tmwtypes.h 
 */
/*
 * Warning - Filter coefficients were truncated to fit specified data type.  
 *   The resulting response may not match generated theoretical response.
 *   Use the Filter Design & Analysis Tool to design accurate
 *   int16 filter coefficients.
 */
#define MWSPT_NSEC 5
const int NL[MWSPT_NSEC] = { 1,3,1,3,1 };
const int16_T NUM[MWSPT_NSEC][3] = {
  {
     1170,      0,      0 
  },
  {
    32767,  32767,  32767 
  },
  {
      986,      0,      0 
  },
  {
    32767,  32767,  32767 
  },
  {
    32767,      0,      0 
  }
};
const int DL[MWSPT_NSEC] = { 1,3,1,3,1 };
const int16_T DEN[MWSPT_NSEC][3] = {
  {
    32767,      0,      0 
  },
  {
    32767, -32768,  24122 
  },
  {
    32767,      0,      0 
  },
  {
    32767, -32768,  15176 
  },
  {
    32767,      0,      0 
  }
};
